name: Deploy to bucket
description: Deploy files to bucket

inputs:
  ENVIRONMENT:
    description: Environment
    required: true

runs:
  using: 'composite'
  steps:
    - name: Current tag
      shell: bash
      run: |
        echo Should release this tag to ${{ inputs.ENVIRONMENT }}
        git describe --tags
    - name: Log current files
      shell: bash
      run: |
        ls
