name: Deploy to bucket
description: Steps to say hello

inputs:
  environment:
    description: Environment
    required: true
  secretInput:
    description: 'ssh'
    required: true
  mode:
    description: Build mode
    required: false
    default: production
  message:
    description: Message
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Current tag
      shell: bash
      run: |
        echo Should release this tag to ${{ inputs.environment }}
        git describe --tags
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Build frontend
      shell: bash
      env:
        VITE_MESSAGE: ${{ inputs.message }}
      run: |
        yarn install
        yarn build --mode ${{ inputs.mode }}
        cd dist/assets/
        cat `ls -1 | grep 'index.*.js'`
    - name: Log current files
      shell: bash
      run: ls
