name: Deploy to bucket
description: Deploy files to bucket

inputs:
  ENVIRONMENT:
    description: Environment
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Current tag
      shell: bash
      run: |
        echo Should release this tag to ${{ inputs.ENVIRONMENT }}
        git describe --tags
        - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Log current files
      shell: bash
      run: |
        echo go to here cd ${{github.action_path}}
        cd ${{github.action_path}}
        cat ${{ inputs.DIST_PATH }}/dist/assets/index.*.js
