name: Deploy to bucket
description: Steps to say hello

inputs:
  environment:
    description: Environment
    required: true
  secretInput:
    description: 'ssh'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Current tag
      shell: bash
      run: |
        echo Should release this tag to ${{ inputs.environment }}
        git describe --tags
    - name: Env secret
      shell: bash
      run: echo ${{ inputs.secretInput }}
    - name: Log current files
      shell: bash
      run: ls
