name: 'Build and deploy release'

on:
  release:
    types: [edited, published]

jobs:
  new_release:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log out information about release
        run: |
          echo Event type that triggered the workflow: ${{ github.event.action }}
          echo PreRelease ${{ github.event.release.prerelease }}
          git describe --tags

  deploy_to_prod:
    if: ${{ !github.event.release.prerelease }}
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: build
        name: Build
        uses: ./.github/actions/build
        with:
          MESSAGE: ${{ secrets.SECRET }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          ENVIRONMENT: 'prod'

  deploy_to_staging:
    if: ${{ github.event.release.prerelease }}
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: build
        name: Build
        uses: ./.github/actions/build
        with:
          MODE: 'staging'
          MESSAGE: ${{ secrets.SECRET }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          ENVIRONMENT: 'staging'
