name: 'Deploy staging'

on:
  workflow_call:

jobs:
  release:
    environment:
      name: staging
    name: Deploy latest whatever release to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Is it prerelease?
        run: echo Prerelease ${{ github.event.release.prerelease }}
      - name: Current tag
        run: git describe --tags
      - name: Env secret
        run: echo ${{ secrets.SECRET }}
