name: 'Deploy prod'

on:
  release:
    types: [edited, published]
  workflow_dispatch:

jobs:
  release:
    if: ${{ !github.event.release.prerelease }}
    name: Deploy latest release (not prerelease) to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Is it prerelease?
        run: echo Prerelease ${{ github.event.release.prerelease }}
      - name: Current tag
        run: git describe --tags
