name: Deploy tag to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy
        type: environment
        required: true
        default: dev

jobs:
  deploy:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - if: ${{ github.event.inputs.environment == prod }}
        name: Deploy to production
        uses: ./.github/workflows/deploy-prod

      - if: ${{ github.event.inputs.environment == staging }}
        name: Deploy to stagin
        uses: ./.github/workflows/deploy-staging
