name: 'Do stuff on release'

on:
  release:
    types: [created, edited, published]

jobs:
  release:
    name: Test stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Current tag'
        run: 'git describe --tags'
