name: 'Do stuff on release'

on:
  release:
    types: [edited, published]

jobs:
  release:
    name: Test stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Is it prerelease?
        run: echo Prerelease ${{ github.event.release.prerelease }}
      - name: Current tag
        run: git describe --tags
      - name: Release staging
        if: ${{ github.event.release.prerelease }}
        uses: './.github/actions/deploy-staging'
      - name: Release production
        if: ${{ !github.event.release.prerelease }}
        uses: './.github/actions/deploy-prod'
